version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: isincountry_postgres
    environment:
      POSTGRES_DB: isincountry_db
      POSTGRES_USER: isincountry_user
      POSTGRES_PASSWORD: isincountry_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: isincountry_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
